# Site settings
title: "FoxHound Espresso"
email: shop@coffeebroaster.com
subtitle: "Espresso & Coffee Broaster"
baseurl: "/cofeebroaster.com"
url: "http://cofeebroaster.com"

# Build settings
markdown: kramdown
