# Site settings
title: "Foxhound Espresso"
email: your-email@domain.com
subtitle: "Espresso & Coffee Broaster"
baseurl: "/cofeebroaster.com"
url: "http://cofeebroaster.com"

# Build settings
markdown: kramdown
